### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by saurabhthorat** [lawloretienne/MovieHub#2]
App crashes immediately on startup after showing the splash screen.

Device: Samsung Galaxy Tab 2 P3100
OS: Lollipop 5.0.2

Here's stack trace for the crash:
[stack_trace.txt](https://github.com/lawloretienne/MovieHub/files/785631/stack_trace.txt)

**Comment by lawloretienne** [comment]
Based on that stack trace it looks like it is having an issue with one of these properties in the `BottomNavigationView`
`app:itemIconTint` or `app:itemTextColor`.

Do you have any other devices to test this on?  I have done most of my testing on my Nexus 5X.  I have not done any testing on a tablet.

**Comment by saurabhthorat** [comment]
I also tested on Yu Yureka running 5.1.1 Lollipop and it crashes on that too.

**Comment by lawloretienne** [comment]
I just created some new devices in AVD to test on.  I tested on a Nexus 5 API 21, Nexus 4 API 22, Nexus 9 API 22, and Nexus 7 API 21.  I could not reproduce this crash on any of these devices.

**Comment by lawloretienne** [comment]
I just uploaded a new release.  It is a minor update.  Please let me know if it is still an issue.

**Comment by lawloretienne** [comment]
It looks like its an issue with the icon tint color state list selector
https://android.googlesource.com/platform/frameworks/support/+/master/design/src/android/support/design/widget/BottomNavigationView.java?autodive=0%2F%2F%2F%2F%2F#135

**Comment by saurabhthorat** [comment]
Can you upload the apk in 'Releases'?

**Comment by lawloretienne** [comment]
Okay i just uploaded the APK to the latest release.  Sorry I forgot to do that.

**Comment by saurabhthorat** [comment]
It is working now without any issues!

**Comment by lawloretienne** [comment]
Oh awesome. So right now the APK is a build that has what is in the `master` branch.  I am currently revamping the whole project in the `mvp`.  I am adding package by feature, mvp design pattern, as well as unit tests and ui tests.  It will take me some time since i'm new to all this stuff.  But hopefully once i get this all sorted out it should be a decent example for other devs.

**Comment by saurabhthorat** [comment]
Great work on the app. Looking forward to it.
